---

<<<<<<< HEAD
- hosts: '{{host}}'
=======
- hosts: controller
>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
  tasks:
  - name: Install chrony
    apt:
     name: chrony
     state: present
  - name: Configure chrony
    shell: |
     NTP_SERVER="mouette.rd.francetelecom.fr"
     echo "server $NTP_SERVER iburst
     allow 192.168.122.0/24" >> /etc/chrony/chrony.conf
     service chrony restart  
  - name : Install mariadb for storage
    apt:
     name: mariadb-server,python-pymysql
     state: present
  - name: Configure mariadb
    shell : |
     echo "[mysqld]
     bind-address = {{ip_address}}
     default-storage-engine = innodb
     innodb_file_per_table = on
     max_connections = 4096
     collation-server = utf8_general_ci
     character-set-server = utf8
     " > /etc/mysql/mariadb.conf.d/99-openstack.cnf


     service mysql restart

     mysql -u root <<EOF
     UPDATE mysql.user SET Password=PASSWORD('${db_root_password}') WHERE User='root';
     DELETE FROM mysql.user WHERE User='';
     DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
     DROP DATABASE IF EXISTS test;
     DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
     FLUSH PRIVILEGES;
     EOF

  - name: Install rabbitmq
    apt:
     name: rabbitmq-server
     state: present

  - name: Configure rabbit
    shell : |
     rabbitmqctl add_user openstack {{password}}
     rabbitmqctl set_permissions openstack ".*" ".*" ".*"


  - name: Install memcached
    apt:
     name: memcached,python-memcache 
     state: present

  - name: Configure memcached
    shell : |
<<<<<<< HEAD
     echo "-l {{ip_address}}"  > /etc/memcached.conf
=======
     echo "-l ${{ip_address}}"  > /etc/memcached.conf
>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
     service memcached restart

  - name: Install etcd
    apt:
     name: etcd 
     state: present

  - name: Configure etcd
    shell : |
     echo "
     ETCD_NAME=\"controller\"
     ETCD_DATA_DIR=\"/var/lib/etcd\"
     ETCD_INITIAL_CLUSTER_STATE=\"new\"
     ETCD_INITIAL_CLUSTER_TOKEN=\"etcd-cluster-01\"
     ETCD_INITIAL_CLUSTER=\"controller=http://{{ip_address}}:2380\"
     ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://{{ip_address}}:2380\"
     ETCD_ADVERTISE_CLIENT_URLS=\"http://{{ip_address}}:2379\"
     ETCD_LISTEN_PEER_URLS=\"http://0.0.0.0:2380\"
     ETCD_LISTEN_CLIENT_URLS=\"http://{{ip_address}}:2379\"
     "> /etc/default/etcd

     systemctl enable etcd
     systemctl start etcd
