---

<<<<<<< HEAD
- hosts: '{{host}}'
  tasks:
  - name : create glance database, openstack image service and endpoints
    shell : |
=======
- hosts: controller
 - name : create glance database, openstack image service and endpoints
   shell : |
>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
     mysql -u root --password={{password}}<<EOF
     CREATE DATABASE glance;
     GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' 
     IDENTIFIED BY '{{password}}';
     GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' 
     IDENTIFIED BY '{{password}}';
     EOF
     openstack user create --domain default --password {{password}} glance

     openstack role add --project service --user glance admin
     openstack service create --name glance \
     --description "OpenStack Image" image

     openstack endpoint create --region RegionOne \
     image public http://controller:9292

     openstack endpoint create --region RegionOne \
     image internal http://controller:9292

     openstack endpoint create --region RegionOne \
     image admin http://controller:9292
<<<<<<< HEAD
  - name: install glance package
    apt:
     name: glance
     state: present
  - name : configure glance and bootstrrap the service
    shell: |
=======
 - name: install glance package
   apt:
     name: glance
     state: present
 - name : configure glance and bootstrrap the service
   shell: |
     cp conf_files/etc_glance_glance-api.conf /etc/glance/glance-api.conf
     cp conf_files/etc_glance_glance-registry.conf /etc/glance/glance-registry.conf

>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
     crudini --set /etc/glance/glance-api.conf database connection "mysql+pymysql://glance:{{password}}@controller/glance"

     crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_uri  http://controller:5000
     crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_url  http://controller:5000
     crudini --set /etc/glance/glance-api.conf keystone_authtoken memcached_servers  controller:11211
     crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_type  password
     crudini --set /etc/glance/glance-api.conf keystone_authtoken project_domain_name  Default
     crudini --set /etc/glance/glance-api.conf keystone_authtoken user_domain_name  Default
     crudini --set /etc/glance/glance-api.conf keystone_authtoken project_name service
     crudini --set /etc/glance/glance-api.conf keystone_authtoken username glance
     crudini --set /etc/glance/glance-api.conf keystone_authtoken password {{password}}

     crudini --set /etc/glance/glance-api.conf paste_deploy flavor keystone


     crudini --set /etc/glance/glance-api.conf glance_store stores  "file,http"
     crudini --set /etc/glance/glance-api.conf glance_store default_store  file
     crudini --set /etc/glance/glance-api.conf glance_store filesystem_store_datadir  "/var/lib/glance/images/"


     crudini --set /etc/glance/glance-registry.conf database connection "mysql+pymysql://glance:{{password}}@controller/glance"


     crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri  http://controller:5000
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_url  http://controller:5000
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken memcached_servers controller:11211
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_type  password
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken project_domain_name  Default
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken user_domain_name  Default
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken project_name  service
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken username  glance
     crudini --set /etc/glance/glance-registry.conf keystone_authtoken password  {{password}}

     crudini --set /etc/glance/glance-registry.conf paste_deploy flavor keystone

     su -s /bin/sh -c "glance-manage db_sync" glance

     service glance-registry restart
     service glance-api restart
