---

- hosts: '{{host}}'

- import_playbook: requirements.yml ip_controller='{{controller_ip_address}}' host='{{host}}'

- import_playbook: nova_compute_installing.yml password='{{password}}'  ip_address='{{ip_address}}' host='{{host}}'

- import_playbook: neutron_compute_installing.yml password='{{password}}' ip_address='{{ip_address}}' interface='{{interface}}' host='{{host}}'
