---
 
<<<<<<< HEAD
- hosts: '{{host}}'
=======
- hosts: CO
>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
  tasks:
  - name : Installing the package
    apt:
     name: neutron-linuxbridge-agent
     state: present
  - name : Configuring the service
    shell: |
<<<<<<< HEAD
=======
      cp conf_files/etc_neutron_plugins_ml2_linuxbridge_agent.ini /etc/neutron/plugins/ml2/linuxbridge_agent.ini
 
>>>>>>> fcf5928dec70ab3fd77188767ade3ffae110c093
      crudini --set /etc/neutron/neutron.conf DEFAULT	transport_url rabbit://openstack:{{password}}@controller
      crudini --set /etc/neutron/neutron.conf DEFAULT	auth_strategy keystone
 
 
      crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://controller:5000
      crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_url http://controller:5000
      crudini --set /etc/neutron/neutron.conf keystone_authtoken memcached_servers controller:11211
      crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_type password
      crudini --set /etc/neutron/neutron.conf keystone_authtoken project_domain_name default
      crudini --set /etc/neutron/neutron.conf keystone_authtoken user_domain_name default
      crudini --set /etc/neutron/neutron.conf keystone_authtoken project_name service
      crudini --set /etc/neutron/neutron.conf keystone_authtoken username neutron
      crudini --set /etc/neutron/neutron.conf keystone_authtoken password {{password}}
 
      crudini --set /etc/neutron/neutron.conf oslo_concurrency lock_path /var/lib/neutron/tmp
 
 
      crudini --set /etc/nova/nova.conf neutron url http://controller:9696
      crudini --set /etc/nova/nova.conf neutron auth_url http://controller:5000
      crudini --set /etc/nova/nova.conf neutron auth_type password
      crudini --set /etc/nova/nova.conf neutron project_domain_name default
      crudini --set /etc/nova/nova.conf neutron user_domain_name default
      crudini --set /etc/nova/nova.conf neutron region_name RegionOne
      crudini --set /etc/nova/nova.conf neutron project_name service
      crudini --set /etc/nova/nova.conf neutron username neutron
      crudini --set /etc/nova/nova.conf neutron password {{password}}
 
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini linux_bridge physical_interface_mappings  provider:{{interface}}
 
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan enable_vxlan true
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan local_ip {{ip_address}}
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan l2_population true
 
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini securitygroup enable_security_group true
 
      crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
 
      service nova-compute restart
   
      service neutron-linuxbridge-agent restart
